version: '3'

services:
  app:
    build:
      context: .
    command: bundle exec unicorn -c /app/config/unicorn.rb -p 3000
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    networks:
      - app-network
    stdin_open: true
    tty: true
  #   depends_on:
  #     - db

  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #     MYSQL_DATABASE: app_development
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   networks:
  #     - app-network

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - app-network

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  app-network:
    external: true
