version: '3'

services:
  app:
    build:
      context: .
    command: bundle exec unicorn -c /app/config/unicorn.rb -E production -p 3000
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    networks:
      - app-network
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: production

  web:
    build:
      context: ./nginx_docker_production
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - app-network

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  app-network:
    external: true
