version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - 90:51:90:e8:73:10:79:2d:dc:41:b0:2b:aa:5c:54:ab
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "/home/ec2-user/PhotoContestApp/deploy-me.sh"
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
