default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: <%= Rails.application.credentials.RDS[:database] %>
  host: <%= Rails.application.credentials.RDS[:host] %>
  username: <%= Rails.application.credentials.RDS[:username] %>
  password: <%= Rails.application.credentials.RDS[:password] %>
